spring:
  config:
    import: optional:file:.env.properties
  profiles:
    active: dev
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  output:
    ansi:
      enabled: always
  datasource:
    hikari:
      auto-commit: false
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: ${KAKAO_CLIENT_ID}
            scope: profile_nickname, profile_image
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: 'http://localhost:8080/login/oauth2/code/kakao'
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
springdoc:
  default-produces-media-type: application/json

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
    com.rest1: DEBUG

custom:
  jwt:
    expireSeconds: "#{30 * 60}"
    secretPattern: ${JWT_SECRET_PATTERN}
